name: iml-project
channels:
  - pytorch
  - conda-forge
  - huggingface
dependencies:
  - python=3.9
  - pytorch=1.10
  - cudatoolkit=11.3
  - transformers=4.16.1
  - datasets=1.18.2
  - captum=0.4.1
  - scikit-learn=1.0.2
  - parameterized=0.8.1